### ISSUE TITLE
Windows build Error

### ISSUE THREAD

**Issue by warlolz999** [DavBfr/dart_pdf#1375]
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)

**Comment by warlolz999** [comment]
[   +3 ms] executing: [C:\Development\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +86 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 84a1e904f44f9b0e9c4510138010edcc653163f8
[        ] executing: [C:\Development\flutter/] git tag --points-at 84a1e904f44f9b0e9c4510138010edcc653163f8
[ +140 ms] Exit code 0 from: git tag --points-at 84a1e904f44f9b0e9c4510138010edcc653163f8
[   +2 ms] 3.10.0
[   +3 ms] executing: [C:\Development\flutter/] git rev-parse --abbrev-ref HEAD
[  +77 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +60 ms] executing: [C:\Development\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +82 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\Development\flutter/] git ls-remote --get-url origin
[  +82 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +145 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +78 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +89 ms] Skipping pub get: version match.
[  +63 ms] Found plugin charset_converter at C:\Users\Eugune Chow\AppData\Local\Pub\Cache\hosted\pub.dev\charset_converter-2.1.1\
[  +24 ms] Found plugin file_picker at C:\Users\Eugune Chow\AppData\Local\Pub\Cache\hosted\pub.dev\file_picker-5.3.0\
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\Eugune Chow\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_plugin_android_lifecycle-2.0.14\
[  +35 ms] Found plugin printing at C:\Users\Eugune Chow\AppData\Local\Pub\Cache\hosted\pub.dev\printing-5.10.4\
[  +77 ms] Found plugin charset_converter at C:\Users\Eugune Chow\AppData\Local\Pub\Cache\hosted\pub.dev\charset_converter-2.1.1\
[  +11 ms] Found plugin file_picker at C:\Users\Eugune Chow\AppData\Local\Pub\Cache\hosted\pub.dev\file_picker-5.3.0\
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\Eugune Chow\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_plugin_android_lifecycle-2.0.14\
[  +32 ms] Found plugin printing at C:\Users\Eugune Chow\AppData\Local\Pub\Cache\hosted\pub.dev\printing-5.10.4\
[ +142 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +75 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +2 ms] [
             {
               "instanceId": "28ea0a6b",
               "installDate": "2022-02-15T01:20:00Z",
               "installationName": "VisualStudio/17.0.6+32126.317",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.0.32126.317",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "学生、オープンソースの共同作成者、個人用の無料で強力な IDE",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",   
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.0#17.0.6",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2022-02-15T01:20:00.0704681Z",
               "catalog": {
                 "buildBranch": "d17.0",
                 "buildVersion": "17.0.32126.317",
                 "id": "VisualStudio/17.0.6+32126.317",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.0.6",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "6",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.0.6+32126.317",
                 "requiredEngineVersion": "3.0.4496.34889"
               },
               "properties": {
                 "campaignId": "2030",
                 "channelManifestId": "VisualStudio.17.Release/17.0.6+32126.317",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[  +15 ms] Building Windows application...
[  +18 ms] executing: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
C:\Development\conveyorsystem\windows -B build\windows -G Visual Studio 17 2022
[ +149 ms] -- Downloading/updating pdfium
[ +660 ms] -- Configuring done
[ +137 ms] -- Generating done
[  +10 ms] -- Build files have been written to: C:/Development/conveyorsystem/build/windows/pdfium-download
[ +191 ms] .NET Framework 向け Microsoft (R) Build Engine バージョン 17.0.0+c9eb9dd64
[   +1 ms] Copyright (C) Microsoft Corporation.All rights reserved.
[ +594 ms]   Performing test step for 'pdfium-download'
[  +10 ms]   'DOWNLOAD_EXTRACT_TIMESTAMP' は、内部コマンドまたは外部コマンド、
[   +1 ms]   操作可能なプログラムまたはバッチ ファイルとして認識されていません。
[  +16 ms] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(242,5): error MSB8066:
'C:\Development\conveyorsystem\build\windows\pdfium-download\CMakeFiles\2e5a11d3a46c162ce0ee047c408a8ade\pdfium-download-test.rule;C:\Development\conveyorsystem\build\win
dows\pdfium-download\CMakeFiles\0746cbacaacabcd36daf888a87f4c167\pdfium-download-complete.rule;C:\Development\conveyorsystem\build\windows\pdfium-download\CMakeFiles\ad0b
c9a1cd01e7044989bf5ff43de9b3\pdfium-download.rule' のカスタム ビルドがコード 9009 で終了しました。 [C:\Development\conveyorsystem\build\windows\pdfium-download\pdfium-download.vcxproj]
[  +74 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
[   +4 ms]   Build step for pdfium failed: 1
[        ] Call Stack (most recent call first):
[        ]   flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)
[   +1 ms] -- Configuring incomplete, errors occurred!
[        ] See also "C:/Development/conveyorsystem/build/windows/CMakeFiles/CMakeOutput.log".
[  +33 ms] Building Windows application... (completed in 1,887ms)
[   +1 ms] "flutter windows" took 2,622ms.
[   +7 ms] Unable to generate build files
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmakeGeneration (package:flutter_tools/src/windows/build_windows.dart:176:5)
           <asynchronous suspension>
           #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:85:5)
           <asynchronous suspension>
           #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:56:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +68 ms] ensureAnalyticsSent: 54ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by Des-Hussain** [comment]
You found any solutions yet?

**Comment by warlolz999** [comment]
> You found any solutions yet?

Nope. I tried setting the version to 5200. 
I also tried flutter clean and flutter run also failed.

**Comment by Des-Hussain** [comment]
printing: 5.10.3
pdf: 3.10.1
try these versions with 
set(PDFIUM_VERSION "4634" CACHE STRING "")
it is finally working for me and make sure your pubspec.lock uses the same version as pubspec.yaml

**Comment by warlolz999** [comment]
> printing: 5.10.3 pdf: 3.10.1 try these versions with set(PDFIUM_VERSION "4634" CACHE STRING "") it is finally working for me and make sure your pubspec.lock uses the same version as pubspec.yaml

ok. I will try.

**Comment by DavBfr** [comment]
The automated build works with no modification: https://github.com/DavBfr/dart_pdf/actions/runs/4947206676/jobs/8846271943

**Comment by warlolz999** [comment]
> The automated build works with no modification: https://github.com/DavBfr/dart_pdf/actions/runs/4947206676/jobs/8846271943

I tried on 2 different PC.
The one failed is Windows 11 with Japanese language pack. The errors as shown above.
On another PC with Windows 10 and English it works.

**Comment by DavBfr** [comment]
@warlolz999 But you're developing in C:\Development so it should not be an issue with a Japanese filename encoding.
Try to open the visual studio project and see if you find something wrong.

**Comment by warlolz999** [comment]
> @warlolz999 But you're developing in C:\Development so it should not be an issue with a Japanese filename encoding. Try to open the visual studio project and see if you find something wrong.

Okay. I will check again tomorrow and reply you.

**Comment by dsternberg** [comment]
You get the error with flutter 3.10.0 and   pdf: ^3.10.3  printing: ^5.10.4. Same Error here with the newest flutter version

**Comment by warlolz999** [comment]
@DavBfr 
'DOWNLOAD_EXTRACT_TIMESTAMP' is not recognized as an internal or external command, operable program or batch file. 

'C:\Development\conveyorsystem\build\windows\pdfium-download\CMakeFiles\ad0bc9a1cd01e7044989bf5ff43de9b3\pdfium-download.rule' custom Build terminated with code 9009.

I found these 2 errors.

**Comment by warlolz999** [comment]
An update for everyone facing this issue.  I updated Visual Studio 2022 to the latest patch and the issue was resolved.
Current verison of Visual Studio 2022 is 17.5.5.

**Comment by amiga115** [comment]
Same error on Windows and Linux build. It happen after updating sdk and vscode

```
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/linux/CMakeLists.txt:36 (download_project)
```

**Comment by DavBfr** [comment]
Fixed in the master branch.

Try it adding this in your `pubspec.yaml`
```yaml
dependency_overrides:
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf
      ref: master
      path: printing
```

**Comment by florianguyot** [comment]
@DavBfr Thanks for the push, but I still face the same issue on Windows even after a `flutter clean` and `flutter pub cache clean`. 

The pubspec.lock indicate your last commit id `198a2ea` so I am sure I am on the pointing on the master branch.

**Comment by Devidas-G** [comment]
> printing: 5.10.3 pdf: 3.10.1 try these versions with set(PDFIUM_VERSION "4634" CACHE STRING "") it is finally working for me and make sure your pubspec.lock uses the same version as pubspec.yaml

this worked for me too after removing

```dependency_overrides: 
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf
      ref: master
      path: printing
```
without the use of 

`set(PDFIUM_VERSION "4634" CACHE STRING "")`

**Comment by richard457** [comment]
C:\Users\U\Documents\flutter3.10.0\app> flutter pub run msix:create
Deprecated. Use `dart run` instead.
Building package executable... (3.3s)
Built msix:create.
running "flutter build windows"...      

Building Windows application...
Building Windows application...                                     5.6s

Unhandled exception:
CMake Error at CMakeLists.txt:9 (cmake_policy):
  Policy "CMP0135" is not known to this version of CMake.


CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:171 (message):
  CMake step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)

**Comment by DavBfr** [comment]
Please try with this in `printing/windows/DownloadProject.CMakeLists.cmake.in`:

```
if(CMAKE_VERSION VERSION_EQUAL "3.24")
  cmake_policy(SET CMP0135 NEW)
endif()
```

**Comment by ultrabalki** [comment]
facing the same issue. i switch 5.10.4 to 5.10.3 in pubspec.lock, without set(...) build successfully.

**Comment by richard457** [comment]
> facing the same issue. i switch 5.10.4 to 5.10.3 in pubspec.lock (make sure to use the right sha256), without set(...) anything in CMakeList, windows build successfully.

It might not build on flutter 3.10.0

**Comment by ultrabalki** [comment]
flutter 3.7.12

**Comment by ultrabalki** [comment]
> flutter 3.7.12

@richard457

**Comment by kay4ik** [comment]
Similar error here: Windows build fails with following error: (flutter build windows)

```
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)
```

Verbose:
```
[   +3 ms] Building Windows application...
[  +11 ms] executing: C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\windows -B build\windows -G Visual Studio 17 2022
[  +84 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
[ +566 ms] Feeds used:
[        ]   C:\Users\FuE-Admin\.nuget\packages\
[        ]   https://api.nuget.org/v3/index.json
[ +100 ms] Das Paket ,Microsoft.Windows.CppWinRT.2.0.201102.2" ist bereits installiert.
[ +557 ms] Feeds used:
[        ]   C:\Users\FuE-Admin\.nuget\packages\
[        ]   https://api.nuget.org/v3/index.json
[  +84 ms] Das Paket ,Microsoft.Windows.CppWinRT.2.0.210806.1" ist bereits installiert.
[ +845 ms] -- Downloading/updating pdfium
[  +29 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
[+1485 ms] -- Configuring done
[  +97 ms] -- Generating done
[   +2 ms] -- Build files have been written to:
D:/builds/BA_pyByX/1/schunk_suite/schunk_cc/build/windows/pdfium-download
[ +104 ms] MSBuild version 17.3.1+2badb37d1 for .NET Framework
[+1571 ms]   Performing test step for 'pdfium-download'
[        ]   Der Befehl "DOWNLOAD_EXTRACT_TIMESTAMP" ist entweder falsch geschrieben oder
[        ]   konnte nicht gefunden werden.
[  +11 ms] C:\Program Files (x86)\Microsoft Visual
Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for
'D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\build\windows\pdfium-download\CMakeFiles\20bb75c829c665977a7ff82305a90320\p
dfium-download-test.rule;D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\build\windows\pdfium-download\CMakeFiles\28b036f76c
490a90ca294608f7a12288\pdfium-download-complete.rule;D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\build\windows\pdfium-do
wnload\CMakeFiles\9a11bff33280e09417884d163eb51c11\pdfium-download.rule' exited with code 9009.
[D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\build\windows\pdfium-download\pdfium-download.vcxproj]
[  +52 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
[   +2 ms]   Build step for pdfium failed: 1
[        ] Call Stack (most recent call first):
[        ]   flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "D:/builds/BA_pyByX/1/schunk_suite/schunk_cc/build/windows/CMakeFiles/CMakeOutput.log".
[  +13 ms] Building Windows application... (completed in 5,6s)
[   +1 ms] "flutter windows" took 6.484ms.
[   +3 ms] Unable to generate build files
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmakeGeneration (package:flutter_tools/src/windows/build_windows.dart:176:5)
           <asynchronous suspension>
           #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:85:5)
           <asynchronous suspension>
           #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:56:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +17 ms] ensureAnalyticsSent: 11ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

and the error of the command ```dart run msix:create```

```
Building package executable... (3.6s)
Built msix:create.
running "flutter build windows"...

Building Windows application...
Building Windows application...                                     5,6s

Unhandled exception:
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)


Unable to generate build files

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:61:7)
#1      WindowsBuild.build (package:msix/src/windows_build.dart:27:9)
<asynchronous suspension>
#2      Msix._buildMsixFiles (package:msix/msix.dart:103:31)
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:98:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:57:5)
<asynchronous suspension>
#5      main (file:///C:/Users/FuE-Admin/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.13.1/bin/create.dart:4:3)
<asynchronous suspension>
```

Output of flutter doctor -v:
```
[✓] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22000.1936], locale de-DE)
    • Flutter version 3.10.1 on channel stable at C:\flutter_build_server\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (5 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\FuE-Admin\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\FuE-Admin\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.78.2)
    • VS Code at C:\Users\FuE-Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1936]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

pubspec.yaml:
```
pdf: ^3.10.3
printing: ^5.10.4
```

I also tried with and without the override you mentioned above, and with and without the pdfium version specification in cMakeLists.

Build Machine info:
- Windows 11 Enterprise, 21H2, 22000.1936

On a win10 machine *flutter build windows* is functioning, but *msix:create* is failing too

I hope this information helps

**Comment by sakshitporwal** [comment]
> Similar error here: Windows build fails with following error: (flutter build windows)
> 
> ```
> CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
>   Build step for pdfium failed: 1
> Call Stack (most recent call first):
>   flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)
> ```
> 
> Verbose:
> 
> ```
> [   +3 ms] Building Windows application...
> [  +11 ms] executing: C:\Program Files (x86)\Microsoft Visual
> Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
> D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\windows -B build\windows -G Visual Studio 17 2022
> [  +84 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
> [ +566 ms] Feeds used:
> [        ]   C:\Users\FuE-Admin\.nuget\packages\
> [        ]   https://api.nuget.org/v3/index.json
> [ +100 ms] Das Paket ,Microsoft.Windows.CppWinRT.2.0.201102.2" ist bereits installiert.
> [ +557 ms] Feeds used:
> [        ]   C:\Users\FuE-Admin\.nuget\packages\
> [        ]   https://api.nuget.org/v3/index.json
> [  +84 ms] Das Paket ,Microsoft.Windows.CppWinRT.2.0.210806.1" ist bereits installiert.
> [ +845 ms] -- Downloading/updating pdfium
> [  +29 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
> [+1485 ms] -- Configuring done
> [  +97 ms] -- Generating done
> [   +2 ms] -- Build files have been written to:
> D:/builds/BA_pyByX/1/schunk_suite/schunk_cc/build/windows/pdfium-download
> [ +104 ms] MSBuild version 17.3.1+2badb37d1 for .NET Framework
> [+1571 ms]   Performing test step for 'pdfium-download'
> [        ]   Der Befehl "DOWNLOAD_EXTRACT_TIMESTAMP" ist entweder falsch geschrieben oder
> [        ]   konnte nicht gefunden werden.
> [  +11 ms] C:\Program Files (x86)\Microsoft Visual
> Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for
> 'D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\build\windows\pdfium-download\CMakeFiles\20bb75c829c665977a7ff82305a90320\p
> dfium-download-test.rule;D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\build\windows\pdfium-download\CMakeFiles\28b036f76c
> 490a90ca294608f7a12288\pdfium-download-complete.rule;D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\build\windows\pdfium-do
> wnload\CMakeFiles\9a11bff33280e09417884d163eb51c11\pdfium-download.rule' exited with code 9009.
> [D:\builds\BA_pyByX\1\schunk_suite\schunk_cc\build\windows\pdfium-download\pdfium-download.vcxproj]
> [  +52 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
> [   +2 ms]   Build step for pdfium failed: 1
> [        ] Call Stack (most recent call first):
> [        ]   flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)
> [        ] -- Configuring incomplete, errors occurred!
> [        ] See also "D:/builds/BA_pyByX/1/schunk_suite/schunk_cc/build/windows/CMakeFiles/CMakeOutput.log".
> [  +13 ms] Building Windows application... (completed in 5,6s)
> [   +1 ms] "flutter windows" took 6.484ms.
> [   +3 ms] Unable to generate build files
> [        ]
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            #1      _runCmakeGeneration (package:flutter_tools/src/windows/build_windows.dart:176:5)
>            <asynchronous suspension>
>            #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:85:5)
>            <asynchronous suspension>
>            #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:56:5)
>            <asynchronous suspension>
>            #4      FlutterCommand.run.<anonymous closure>
> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
>            <asynchronous suspension>
>            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
>            <asynchronous suspension>
>            #7      FlutterCommandRunner.runCommand.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
>            <asynchronous suspension>
>            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
>            <asynchronous suspension>
>            #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
>            <asynchronous suspension>
>            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #12     main (package:flutter_tools/executable.dart:91:3)
>            <asynchronous suspension>
> 
> 
> [  +17 ms] ensureAnalyticsSent: 11ms
> [        ] Running 0 shutdown hooks
> [        ] Shutdown hooks complete
> [        ] exiting with code 1
> ```
> 
> and the error of the command `dart run msix:create`
> 
> ```
> Building package executable... (3.6s)
> Built msix:create.
> running "flutter build windows"...
> 
> Building Windows application...
> Building Windows application...                                     5,6s
> 
> Unhandled exception:
> CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
>   Build step for pdfium failed: 1
> Call Stack (most recent call first):
>   flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)
> 
> 
> Unable to generate build files
> 
> #0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:61:7)
> #1      WindowsBuild.build (package:msix/src/windows_build.dart:27:9)
> <asynchronous suspension>
> #2      Msix._buildMsixFiles (package:msix/msix.dart:103:31)
> <asynchronous suspension>
> #3      Msix._createMsix (package:msix/msix.dart:98:5)
> <asynchronous suspension>
> #4      Msix.create (package:msix/msix.dart:57:5)
> <asynchronous suspension>
> #5      main (file:///C:/Users/FuE-Admin/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.13.1/bin/create.dart:4:3)
> <asynchronous suspension>
> ```
> 
> Output of flutter doctor -v:
> 
> ```
> [✓] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22000.1936], locale de-DE)
>     • Flutter version 3.10.1 on channel stable at C:\flutter_build_server\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision d3d8effc68 (5 days ago), 2023-05-16 17:59:05 -0700
>     • Engine revision b4fb11214d
>     • Dart version 3.0.1
>     • DevTools version 2.23.1
> 
> [✓] Windows Version (Installed version of Windows is version 10 or higher)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
>     • Android SDK at C:\Users\FuE-Admin\AppData\Local\Android\Sdk
>     • Platform android-33, build-tools 33.0.0
>     • ANDROID_HOME = C:\Users\FuE-Admin\AppData\Local\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.4)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
>     • Visual Studio Build Tools 2022 version 17.3.32901.215
>     • Windows 10 SDK version 10.0.19041.0
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
> 
> [✓] VS Code (version 1.78.2)
>     • VS Code at C:\Users\FuE-Admin\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.64.0
> 
> [✓] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1936]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.93
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> • No issues found!
> ```
> 
> pubspec.yaml:
> 
> ```
> pdf: ^3.10.3
> printing: ^5.10.4
> ```
> 
> I also tried with and without the override you mentioned above, and with and without the pdfium version specification in cMakeLists.
> 
> Build Machine info:
> 
> * Windows 11 Enterprise, 21H2, 22000.1936
> 
> On a win10 machine _flutter build windows_ is functioning, but _msix:create_ is failing too
> 
> I hope this information helps

Have you been able to find a solution and can make it run.
I tried running on two system; works on one and dosen't on other. Both have identical visual studio and flutter build

**Comment by KevinBrendel** [comment]
I think I got it to properly compile by upgrading to the latest packages (both pdf as well as printing) and by switching the compiler from amd64_x86 to amd64 (so check that you don't accidentally have the wrong compiler selected).

**Comment by frontend-arfoon** [comment]
I ma also stack on with verion of:
