### ISSUE TITLE
Error: No named parameter with the name 'bytesOffset'.

### ISSUE THREAD

**Issue by DavidHCox** [DavBfr/dart_pdf#1396]
**Describe the bug**
Using Flutter 3.10.1. When debugging we get the below error. You can see that the issue is in the raster.dart:132 with the bytesOffset parameter. When commenting that out, going back to my app, and running flutter pub get it works fine.

**Expected behavior**
To build correctly and not throw this error.

**Screenshots**
<img width="561" alt="Screenshot 2023-05-24 at 11 11 10 AM" src="https://github.com/DavBfr/dart_pdf/assets/12649949/3d7756fd-8268-458c-9084-c0558e25f332">
<img width="534" alt="Screenshot 2023-05-24 at 11 04 30 AM" src="https://github.com/DavBfr/dart_pdf/assets/12649949/000a74d2-9c63-41d0-b4cd-424cca7f5f24">

**Flutter Doctor**
```
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
    • Flutter version 3.10.1 on channel stable at /Users/davidcox/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (8 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/davidcox/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Users/davidcox/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.8214.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 4CEB1F66-FB7F-4BF6-8FEC-2BB854F72E39 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser
 - [ ] Windows
 - [ ] Linux

**Comment by t-kietzmann** [comment]
Same issue with 3.10.2 on iOS, can not start the debugger - build fails:

Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/pdf-3.10.3/lib/src/pdf/raster.dart:132:7: Error: No named parameter with the name 'bytesOffset'.

I am using pdf 3.10.3 and printing 5.10.4

**Comment by DavBfr** [comment]
Should be fixed with printing 5.11

**Comment by djcali570** [comment]
I am using printing 5.11.0 and pdf 3.10.4 and still getting the same error. Fails to build for iOS.  Any ideas on how to fix? Thanks.

**Comment by novas1r1** [comment]
I have set a dependency_override to "printing: ^5.11.0" but it still throws the same error message.

**Comment by carlosamurillo** [comment]
Same error. Do you have a provisional solution?

**Comment by djcali570** [comment]
Please check that the latest image package is updated using 'pub upgrade image' I'm had to upgrade to image-4.0.13. This solved the issue for me. 
The bytesOffset parameter is available in that version.

Hope this helps.

**Comment by DavidHCox** [comment]
Seems to be working in pdf 3.10.4. Thanks.

**Comment by Xsantosh** [comment]
Not working with PDF 3.10.4 but it worked with Image:4.0.13

**Comment by DavidHCox** [comment]
Yeah apparently my team is still having the same issue with this too.

**Comment by fredecodes** [comment]
I am getting this same error.  Using pdf 3.10.4, and deps shows that it's using image 4.0.13.  Looking at the code, the named parameter does exist, so not sure what's going on here.  Anybody else find a solution for this?  I've run flutter clean and rebuild pods.

**Comment by novas1r1** [comment]
@fredecodes had the same issue again today. "flutter pub upgrade image" did the trick and fixed it. Have you tried that already?

**Comment by fredecodes** [comment]
Thanks, yes I did that and it fixed it.  Seems odd that it is required though, I wonder if there is some dependency not set correctly in the pdf project.  Never had to do that before.
