### ISSUE TITLE
Windows Build issue

### ISSUE THREAD

**Issue by selvam920** [DavBfr/dart_pdf#854]
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)

Exception: Unable to generate build files
Exited (sigterm)
Flutter 2.6.0-12.0.pre.723 • channel master • https://github.com/flutter/flutter.git
Framework • revision 245168f85c (14 hours ago) • 2021-11-15 12:55:32 -0800
Engine • revision 2962099077
Tools • Dart 2.16.0 (build 2.16.0-14.0.dev) • DevTools 2.8.0

**Comment by DavBfr** [comment]
Fixed in printing-5.6.2. Not released yet.

**Comment by hillelcoren** [comment]
We're still seeing this error using 5.6.3, please see my comment here: https://github.com/DavBfr/dart_pdf/issues/646#issuecomment-970236331
