### ISSUE TITLE
Windows version not building?

### ISSUE THREAD

**Issue by ArchV12** [DavBfr/dart_pdf#972]
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:36 (download_project)

Exception: Unable to generate build files

This is with version 5.7.2.  I've cleaned and all that.   I've also done tons of google search. I see posts on this issue, and posts saying it was resolved a long time ago, but.. it's back?

**Comment by ggdream** [comment]
Your network can't download it, may be. You could try it again and again.

**Comment by ArchV12** [comment]
> Your network can't download it, may be. You could try it again and again.

Doubt that's it, my network is solid... that and I've tried it multiple times over the past couple days.  Always the same result.

**Comment by DavBfr** [comment]
Should be fixed with printing-5.7.3

**Comment by ArchV12** [comment]
Hate to be the bearer of bad news, but its still happening in 5.7.3 as well. (after a clean and all that).
![image](https://user-images.githubusercontent.com/27385425/158027092-013e1e8f-4ef5-415a-8716-b9a371bf011e.png)

**Comment by DavBfr** [comment]
What's your `flutter doctor -v` like?

**Comment by ArchV12** [comment]
> What's your `flutter doctor -v` like?

Got it fixed, see my edit above :)  Thank for the quick response and the fix!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by D2Wirexia** [comment]
I've the same problem when starting windows, changing the version doesn't help!
flutter version - 3.0.5 (stable)
dart version - 2.17.6
printing - 5.9.2

Changing the link to _windows/flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt_ doesn't help, but if I follow the link the pdfium downloads successfully to my computer. Also I added **set(PDFIUM_VERSION "4929" CACHE STRING "" FORCE)** to _windows/CMakeLists.txt_. Inside _.../ephemeral/.plugin_symlinks/printing_ installed pdf version 3.7.2.

Does anyone know what the problem is? This is not the first time.

**Comment by DavBfr** [comment]
@D2Wirexia run `flutter build windows -v` to see what's wrong.

**Comment by D2Wirexia** [comment]
> @D2Wirexia run `flutter build windows -v` to see what's wrong.

[   +3 ms] Building Windows application...
[  +14 ms] executing: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S D:\my-app\windows -B build\windows -G Visual Studio 17 2022
[  +50 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
[  +28 ms] -- Downloading/updating pdfium
[  +29 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
[ +377 ms] -- Configuring done
[  +46 ms] -- Generating done
[   +3 ms] -- Build files have been written to: D:/my-app/build/windows/pdfium-download
[  +83 ms] Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
[ +371 ms]   Performing download step (download, verify and extract) for 'pdfium-download'
[  +18 ms]   -- File already exists but no hash specified (use URL_HASH):
[        ]     file='D:/my-app/build/windows/pdfium-download/pdfium-download-prefix/src/pdfium-windows-x64.zip'
[        ]   Old file will be removed and new file downloaded from URL.
[        ]   -- Downloading...
[        ]      dst='D:/my-app/build/windows/pdfium-download/pdfium-download-prefix/src/pdfium-windows-x64.zip'
[        ]      timeout='none'
[        ]      inactivity timeout='none'
[        ]   -- Using src='https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/4634/pdfium-windows-x64.zip'
[ +554 ms]   -- [download 0% complete]
[  +17 ms]   -- [download 100% complete]
[   +1 ms]   -- Downloading... done
[  +43 ms]   -- extracting...
[        ]        src='D:/my-app/build/windows/pdfium-download/pdfium-download-prefix/src/pdfium-windows-x64.zip'
[        ]        dst='D:/my-app/build/windows/pdfium-src'
[        ]   -- extracting... [tar xfz]
[ +165 ms]   -- extracting... [analysis]
[   +1 ms]   -- extracting... [rename]
[   +5 ms]   -- extracting... [clean up]
[        ]   -- extracting... done
[  +24 ms]   No update step for 'pdfium-download'
[  +39 ms]   No patch step for 'pdfium-download'
[  +38 ms]   No configure step for 'pdfium-download'
[  +46 ms]   No build step for 'pdfium-download'
[  +37 ms]   No install step for 'pdfium-download'
[  +38 ms]   No test step for 'pdfium-download'
[  +38 ms]   Completed 'pdfium-download'
[ +100 ms] -- Downloading/updating pdfium
[  +29 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
[ +370 ms] -- Configuring done
[  +41 ms] -- Generating done
[   +2 ms] -- Build files have been written to: D:/my-app/build/windows/pdfium-download
[  +79 ms] Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
[ +370 ms]   Performing download step (download, verify and extract) for 'pdfium-download'
[  +17 ms]   -- File already exists but no hash specified (use URL_HASH):
[        ]     file='D:/my-app/build/windows/pdfium-download/pdfium-download-prefix/src/pdfium-win-x64.tgz'
[        ]   Old file will be removed and new file downloaded from URL.
[        ]   -- Downloading...
[        ]      dst='D:/my-app/build/windows/pdfium-download/pdfium-download-prefix/src/pdfium-win-x64.tgz'
[        ]      timeout='none'
[        ]      inactivity timeout='none'
[        ]   -- Using src='https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/4634/pdfium-win-x64.tgz'
[ +238 ms]   CMake Error at pdfium-download/pdfium-download-prefix/src/pdfium-download-stamp/download-pdfium-download.cmake:170 (message):
[   +2 ms]     Each download failed!
[  +14 ms] CUSTOMBUILD : error : downloading 'https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/4634/pdfium-win-x64.tgz' failed
[D:\my-app\build\windows\pdfium-download\pdfium-download.vcxproj]
[   +2 ms]             status_code: 22
[   +1 ms]             status_string: "HTTP response code said error"
[   +1 ms]             log:
[        ]             --- LOG BEGIN ---
[        ]             timeout on name lookup is not supported
[        ]       Trying 140.82.121.3:443...
[        ]     Connected to github.com (140.82.121.3) port 443 (#0)
[        ]     schannel: disabled automatic use of client certificate
[        ]     schannel: ALPN, offering h2
[        ]     schannel: ALPN, offering http/1.1
[        ]     schannel: ALPN, server accepted to use h2
[        ]     Using HTTP2, server supports multiplexing
[        ]     Connection state changed (HTTP/2 confirmed)
[        ]     Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
[        ]     len=0
[        ]     Using Stream ID: 1 (easy handle 0x21815add510)
[        ]     GET
[        ]     /bblanchon/pdfium-binaries/releases/download/chromium/4634/pdfium-win-x64.tgz
[        ]     HTTP/2
[        ]     Host: github.com
[        ]     user-agent: curl/7.79.1
[        ]     accept: */*
[        ]     HTTP/2 404
[        ]     server: GitHub.com
[        ]     date: Thu, 11 Aug 2022 10:07:00 GMT
[        ]     content-type: text/plain; charset=utf-8
[        ]     vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding,
[        ]     Accept, X-Requested-With
[        ]     permissions-policy: interest-cohort=()
[        ]     cache-control: no-cache
[        ]     strict-transport-security: max-age=31536000; includeSubdomains; preload
[        ]     x-frame-options: deny
[        ]     x-content-type-options: nosniff
[        ]     x-xss-protection: 0
[        ]     referrer-policy: no-referrer-when-downgrade
[        ]     expect-ct: max-age=2592000,
[        ]     report-uri="https://api.github.com/_private/browser/errors"
[        ]     content-security-policy: default-src 'none'; base-uri 'self'; connect-src
[        ]     'self'; form-action 'self'; img-src 'self' data:; script-src 'self';
[        ]     style-src 'unsafe-inline'
[        ]     content-length: 9
[        ]     x-github-request-id: 0BF3:9038:36331A:3A5893:62F4D4D7
[        ] CUSTOMBUILD : The requested URL returned error : 404 [D:\my-app\build\windows\pdfium-download\pdfium-download.vcxproj]
[        ]     stopped the pause stream!
[        ]     Connection #0 to host github.com left intact
[        ]             --- LOG END ---
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(245,5): error MSB8066: custom assembly for "D:\my-app\build\windows\pdfium-download\CMakeFiles\426f74f35fabfb10ecc04b43640cb731\pdfium-download-download.rule;D:\my-app\build\windows\pdfium-download\CMakeFiles\426f74f35fab
fb10ecc04b43640cb731\pdfium-download-update.rule;D:\my-app\build\windows\pdfium-download\CMakeFiles\426f74f35fabfb10ecc04b43640cb731\pdfium-download-patch.rule;D:\my-app\build\wi
ndows\pdfium-download\CMakeFiles\426f74f35fabfb10ecc04b43640cb731\pdfium-download-configure.rule;D:\my-app\build\windows\pdfium-download\CMakeFiles\426f74f35fabfb10ecc04b43640cb731\pdfium-download-build.ru
le;D:\my-app\build\windows\pdfium-download\CMakeFiles\426f74f35fabfb10ecc04b43640cb731\pdfium-download-install.rule;D:\my-app\build\windows\pdfium-download\CMakeFiles\426f74f35fa
bfb10ecc04b43640cb731\pdfium-download-test.rule;D:\my-app\build\windows\pdfium-download\CMakeFiles\7108d8f791ff102af8cf966355bfba29\pdfium-download-complete.rule;D:\my-app\build\
windows\pdfium-download\CMakeFiles\b2ccb4c04b8444c646a440dd0ef79693\pdfium-download.rule" completed work with code 1. [D:\my-app\build\windows\pdfium-download\pdfium-download.vcxproj]
**[   +6 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
[   +1 ms]   Build step for pdfium failed: 1
[        ] Call Stack (most recent call first):
[        ]   flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:26 (download_project)**
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "D:/my-app/build/windows/CMakeFiles/CMakeOutput.log".
[  +12 ms] Building Windows application... (completed in 4,8s)
[   +1 ms] "flutter windows" took 5 455ms.
**[   +4 ms] Unable to generate build files**

**Comment by DavBfr** [comment]
Why would it download 2 versions of the pdfium DLLs? Have you run `flutter clean`?
If you have a fixed version somewhere in your project, remove it or set it to a more recent version, like 5200.
Search for the string `4634` in all your project.

**Comment by D2Wirexia** [comment]
> Why would it download 2 versions of the pdfium DLLs? Have you run `flutter clean`? If you have a fixed version somewhere in your project, remove it or set it to a more recent version, like 5200. Search for the string `4634` in all your project.

Now managed to launch, but for some reason at `flutter clean` and `pug get` dependencies with other versions are established, such as `4634`.

This error has occurred 3 times now and each time something new helps... I'll keep an eye on it, ty!

**Comment by SwiftiSwift** [comment]
This issue still exists on windows and it is stupid. There should be a permanent fix for this. Setting the pdfium version etc. does not help.

**Comment by mwaimbaroger** [comment]
I had to update my visual studio 2022 for it to work.
